// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/kaze.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KazeService_RegisterWorker_FullMethodName   = "/kaze.KazeService/RegisterWorker"
	KazeService_Heartbeat_FullMethodName        = "/kaze.KazeService/Heartbeat"
	KazeService_SubmitJob_FullMethodName        = "/kaze.KazeService/SubmitJob"
	KazeService_StreamLogs_FullMethodName       = "/kaze.KazeService/StreamLogs"
	KazeService_ListWorkers_FullMethodName      = "/kaze.KazeService/ListWorkers"
	KazeService_GetJobStatus_FullMethodName     = "/kaze.KazeService/GetJobStatus"
	KazeService_ListJobs_FullMethodName         = "/kaze.KazeService/ListJobs"
	KazeService_UpdateJobStatus_FullMethodName  = "/kaze.KazeService/UpdateJobStatus"
	KazeService_WatchLogs_FullMethodName        = "/kaze.KazeService/WatchLogs"
	KazeService_DeregisterWorker_FullMethodName = "/kaze.KazeService/DeregisterWorker"
)

// KazeServiceClient is the client API for KazeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- CORE SERVICE ---
type KazeServiceClient interface {
	// Worker -> Master: Announce presence and capabilities
	RegisterWorker(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Worker -> Master: Periodic health check
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Client -> Master: Submit a new job
	SubmitJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	// Worker <-> Master: Bi-directional log streaming
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogFrame, LogControl], error)
	// Client -> Master: List registered workers
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	// Client -> Master: Get status of a specific job
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error)
	// Client -> Master: List all jobs
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// Worker -> Master: Update job progress and status
	UpdateJobStatus(ctx context.Context, in *UpdateJobStatusRequest, opts ...grpc.CallOption) (*UpdateJobStatusResponse, error)
	// Client -> Master: Watch logs of a specific job in real-time
	WatchLogs(ctx context.Context, in *WatchLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogFrame], error)
	// Worker -> Master: Gracefully announce shutdown / deregistration
	DeregisterWorker(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
}

type kazeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKazeServiceClient(cc grpc.ClientConnInterface) KazeServiceClient {
	return &kazeServiceClient{cc}
}

func (c *kazeServiceClient) RegisterWorker(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, KazeService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kazeServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, KazeService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kazeServiceClient) SubmitJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, KazeService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kazeServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogFrame, LogControl], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KazeService_ServiceDesc.Streams[0], KazeService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogFrame, LogControl]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KazeService_StreamLogsClient = grpc.BidiStreamingClient[LogFrame, LogControl]

func (c *kazeServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, KazeService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kazeServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusResponse)
	err := c.cc.Invoke(ctx, KazeService_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kazeServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, KazeService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kazeServiceClient) UpdateJobStatus(ctx context.Context, in *UpdateJobStatusRequest, opts ...grpc.CallOption) (*UpdateJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobStatusResponse)
	err := c.cc.Invoke(ctx, KazeService_UpdateJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kazeServiceClient) WatchLogs(ctx context.Context, in *WatchLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KazeService_ServiceDesc.Streams[1], KazeService_WatchLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchLogsRequest, LogFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KazeService_WatchLogsClient = grpc.ServerStreamingClient[LogFrame]

func (c *kazeServiceClient) DeregisterWorker(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, KazeService_DeregisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KazeServiceServer is the server API for KazeService service.
// All implementations must embed UnimplementedKazeServiceServer
// for forward compatibility.
//
// --- CORE SERVICE ---
type KazeServiceServer interface {
	// Worker -> Master: Announce presence and capabilities
	RegisterWorker(context.Context, *WorkerInfo) (*RegisterResponse, error)
	// Worker -> Master: Periodic health check
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Client -> Master: Submit a new job
	SubmitJob(context.Context, *JobRequest) (*JobResponse, error)
	// Worker <-> Master: Bi-directional log streaming
	StreamLogs(grpc.BidiStreamingServer[LogFrame, LogControl]) error
	// Client -> Master: List registered workers
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	// Client -> Master: Get status of a specific job
	GetJobStatus(context.Context, *GetJobStatusRequest) (*JobStatusResponse, error)
	// Client -> Master: List all jobs
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	// Worker -> Master: Update job progress and status
	UpdateJobStatus(context.Context, *UpdateJobStatusRequest) (*UpdateJobStatusResponse, error)
	// Client -> Master: Watch logs of a specific job in real-time
	WatchLogs(*WatchLogsRequest, grpc.ServerStreamingServer[LogFrame]) error
	// Worker -> Master: Gracefully announce shutdown / deregistration
	DeregisterWorker(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	mustEmbedUnimplementedKazeServiceServer()
}

// UnimplementedKazeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKazeServiceServer struct{}

func (UnimplementedKazeServiceServer) RegisterWorker(context.Context, *WorkerInfo) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedKazeServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedKazeServiceServer) SubmitJob(context.Context, *JobRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedKazeServiceServer) StreamLogs(grpc.BidiStreamingServer[LogFrame, LogControl]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedKazeServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedKazeServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*JobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedKazeServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedKazeServiceServer) UpdateJobStatus(context.Context, *UpdateJobStatusRequest) (*UpdateJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateJobStatus not implemented")
}
func (UnimplementedKazeServiceServer) WatchLogs(*WatchLogsRequest, grpc.ServerStreamingServer[LogFrame]) error {
	return status.Error(codes.Unimplemented, "method WatchLogs not implemented")
}
func (UnimplementedKazeServiceServer) DeregisterWorker(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterWorker not implemented")
}
func (UnimplementedKazeServiceServer) mustEmbedUnimplementedKazeServiceServer() {}
func (UnimplementedKazeServiceServer) testEmbeddedByValue()                     {}

// UnsafeKazeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KazeServiceServer will
// result in compilation errors.
type UnsafeKazeServiceServer interface {
	mustEmbedUnimplementedKazeServiceServer()
}

func RegisterKazeServiceServer(s grpc.ServiceRegistrar, srv KazeServiceServer) {
	// If the following call panics, it indicates UnimplementedKazeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KazeService_ServiceDesc, srv)
}

func _KazeService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KazeServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KazeService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KazeServiceServer).RegisterWorker(ctx, req.(*WorkerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _KazeService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KazeServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KazeService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KazeServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KazeService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KazeServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KazeService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KazeServiceServer).SubmitJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KazeService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KazeServiceServer).StreamLogs(&grpc.GenericServerStream[LogFrame, LogControl]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KazeService_StreamLogsServer = grpc.BidiStreamingServer[LogFrame, LogControl]

func _KazeService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KazeServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KazeService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KazeServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KazeService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KazeServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KazeService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KazeServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KazeService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KazeServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KazeService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KazeServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KazeService_UpdateJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KazeServiceServer).UpdateJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KazeService_UpdateJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KazeServiceServer).UpdateJobStatus(ctx, req.(*UpdateJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KazeService_WatchLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KazeServiceServer).WatchLogs(m, &grpc.GenericServerStream[WatchLogsRequest, LogFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KazeService_WatchLogsServer = grpc.ServerStreamingServer[LogFrame]

func _KazeService_DeregisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KazeServiceServer).DeregisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KazeService_DeregisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KazeServiceServer).DeregisterWorker(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KazeService_ServiceDesc is the grpc.ServiceDesc for KazeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KazeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kaze.KazeService",
	HandlerType: (*KazeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _KazeService_RegisterWorker_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _KazeService_Heartbeat_Handler,
		},
		{
			MethodName: "SubmitJob",
			Handler:    _KazeService_SubmitJob_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _KazeService_ListWorkers_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _KazeService_GetJobStatus_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _KazeService_ListJobs_Handler,
		},
		{
			MethodName: "UpdateJobStatus",
			Handler:    _KazeService_UpdateJobStatus_Handler,
		},
		{
			MethodName: "DeregisterWorker",
			Handler:    _KazeService_DeregisterWorker_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _KazeService_StreamLogs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchLogs",
			Handler:       _KazeService_WatchLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/kaze.proto",
}
