// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/kaze.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchLogsRequest) Reset() {
	*x = WatchLogsRequest{}
	mi := &file_proto_kaze_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchLogsRequest) ProtoMessage() {}

func (x *WatchLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchLogsRequest.ProtoReflect.Descriptor instead.
func (*WatchLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{0}
}

func (x *WatchLogsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_proto_kaze_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_kaze_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{2}
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobStatusResponse   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_kaze_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{3}
}

func (x *ListJobsResponse) GetJobs() []*JobStatusResponse {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type UpdateJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobStatusRequest) Reset() {
	*x = UpdateJobStatusRequest{}
	mi := &file_proto_kaze_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobStatusRequest) ProtoMessage() {}

func (x *UpdateJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateJobStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateJobStatusRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UpdateJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobStatusResponse) Reset() {
	*x = UpdateJobStatusResponse{}
	mi := &file_proto_kaze_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobStatusResponse) ProtoMessage() {}

func (x *UpdateJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateJobStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	RetryCount    int32                  `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	CronSpec      string                 `protobuf:"bytes,6,opt,name=cron_spec,json=cronSpec,proto3" json:"cron_spec,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	RequiredCpu   float32                `protobuf:"fixed32,8,opt,name=required_cpu,json=requiredCpu,proto3" json:"required_cpu,omitempty"`
	RequiredRamMb int64                  `protobuf:"varint,9,opt,name=required_ram_mb,json=requiredRamMb,proto3" json:"required_ram_mb,omitempty"`
	RequiredTags  map[string]string      `protobuf:"bytes,10,rep,name=required_tags,json=requiredTags,proto3" json:"required_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_proto_kaze_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{6}
}

func (x *JobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatusResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatusResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *JobStatusResponse) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *JobStatusResponse) GetCronSpec() string {
	if x != nil {
		return x.CronSpec
	}
	return ""
}

func (x *JobStatusResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *JobStatusResponse) GetRequiredCpu() float32 {
	if x != nil {
		return x.RequiredCpu
	}
	return 0
}

func (x *JobStatusResponse) GetRequiredRamMb() int64 {
	if x != nil {
		return x.RequiredRamMb
	}
	return 0
}

func (x *JobStatusResponse) GetRequiredTags() map[string]string {
	if x != nil {
		return x.RequiredTags
	}
	return nil
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_proto_kaze_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{7}
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*WorkerStatus        `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_proto_kaze_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{8}
}

func (x *ListWorkersResponse) GetWorkers() []*WorkerStatus {
	if x != nil {
		return x.Workers
	}
	return nil
}

type WorkerStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkerId          string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Hostname          string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CpuUsage          float32                `protobuf:"fixed32,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsageBytes     int64                  `protobuf:"varint,5,opt,name=ram_usage_bytes,json=ramUsageBytes,proto3" json:"ram_usage_bytes,omitempty"`
	LastHeartbeatUnix int64                  `protobuf:"varint,6,opt,name=last_heartbeat_unix,json=lastHeartbeatUnix,proto3" json:"last_heartbeat_unix,omitempty"`
	CpuCount          int32                  `protobuf:"varint,7,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	RamBytes          int64                  `protobuf:"varint,8,opt,name=ram_bytes,json=ramBytes,proto3" json:"ram_bytes,omitempty"`
	Tags              map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	mi := &file_proto_kaze_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{9}
}

func (x *WorkerStatus) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerStatus) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerStatus) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *WorkerStatus) GetRamUsageBytes() int64 {
	if x != nil {
		return x.RamUsageBytes
	}
	return 0
}

func (x *WorkerStatus) GetLastHeartbeatUnix() int64 {
	if x != nil {
		return x.LastHeartbeatUnix
	}
	return 0
}

func (x *WorkerStatus) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *WorkerStatus) GetRamBytes() int64 {
	if x != nil {
		return x.RamBytes
	}
	return 0
}

func (x *WorkerStatus) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CpuCount      int32                  `protobuf:"varint,3,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	RamBytes      int64                  `protobuf:"varint,4,opt,name=ram_bytes,json=ramBytes,proto3" json:"ram_bytes,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_kaze_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{10}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerInfo) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *WorkerInfo) GetRamBytes() int64 {
	if x != nil {
		return x.RamBytes
	}
	return 0
}

func (x *WorkerInfo) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_kaze_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsageBytes int64                  `protobuf:"varint,3,opt,name=ram_usage_bytes,json=ramUsageBytes,proto3" json:"ram_usage_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_kaze_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetRamUsageBytes() int64 {
	if x != nil {
		return x.RamUsageBytes
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_kaze_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"` // Optional for Docker driver
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	CronSpec      string                 `protobuf:"bytes,4,opt,name=cron_spec,json=cronSpec,proto3" json:"cron_spec,omitempty"` // e.g. "*/5 * * * *"
	RetryLimit    int32                  `protobuf:"varint,5,opt,name=retry_limit,json=retryLimit,proto3" json:"retry_limit,omitempty"`
	RequiredCpu   float32                `protobuf:"fixed32,6,opt,name=required_cpu,json=requiredCpu,proto3" json:"required_cpu,omitempty"`
	RequiredRamMb int64                  `protobuf:"varint,7,opt,name=required_ram_mb,json=requiredRamMb,proto3" json:"required_ram_mb,omitempty"`
	RequiredTags  map[string]string      `protobuf:"bytes,8,rep,name=required_tags,json=requiredTags,proto3" json:"required_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_kaze_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{14}
}

func (x *JobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *JobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *JobRequest) GetCronSpec() string {
	if x != nil {
		return x.CronSpec
	}
	return ""
}

func (x *JobRequest) GetRetryLimit() int32 {
	if x != nil {
		return x.RetryLimit
	}
	return 0
}

func (x *JobRequest) GetRequiredCpu() float32 {
	if x != nil {
		return x.RequiredCpu
	}
	return 0
}

func (x *JobRequest) GetRequiredRamMb() int64 {
	if x != nil {
		return x.RequiredRamMb
	}
	return 0
}

func (x *JobRequest) GetRequiredTags() map[string]string {
	if x != nil {
		return x.RequiredTags
	}
	return nil
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_proto_kaze_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{15}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LogFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	StreamType    string                 `protobuf:"bytes,4,opt,name=stream_type,json=streamType,proto3" json:"stream_type,omitempty"` // stdout or stderr
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFrame) Reset() {
	*x = LogFrame{}
	mi := &file_proto_kaze_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFrame) ProtoMessage() {}

func (x *LogFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFrame.ProtoReflect.Descriptor instead.
func (*LogFrame) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{16}
}

func (x *LogFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LogFrame) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *LogFrame) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *LogFrame) GetStreamType() string {
	if x != nil {
		return x.StreamType
	}
	return ""
}

type LogControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stop          bool                   `protobuf:"varint,1,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogControl) Reset() {
	*x = LogControl{}
	mi := &file_proto_kaze_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogControl) ProtoMessage() {}

func (x *LogControl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogControl.ProtoReflect.Descriptor instead.
func (*LogControl) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{17}
}

func (x *LogControl) GetStop() bool {
	if x != nil {
		return x.Stop
	}
	return false
}

var File_proto_kaze_proto protoreflect.FileDescriptor

const file_proto_kaze_proto_rawDesc = "" +
	"\n" +
	"\x10proto/kaze.proto\x12\x04kaze\")\n" +
	"\x10WatchLogsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x11\n" +
	"\x0fListJobsRequest\"?\n" +
	"\x10ListJobsResponse\x12+\n" +
	"\x04jobs\x18\x01 \x03(\v2\x17.kaze.JobStatusResponseR\x04jobs\"_\n" +
	"\x16UpdateJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"3\n" +
	"\x17UpdateJobStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa4\x03\n" +
	"\x11JobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCount\x12\x1b\n" +
	"\tcron_spec\x18\x06 \x01(\tR\bcronSpec\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\x12!\n" +
	"\frequired_cpu\x18\b \x01(\x02R\vrequiredCpu\x12&\n" +
	"\x0frequired_ram_mb\x18\t \x01(\x03R\rrequiredRamMb\x12N\n" +
	"\rrequired_tags\x18\n" +
	" \x03(\v2).kaze.JobStatusResponse.RequiredTagsEntryR\frequiredTags\x1a?\n" +
	"\x11RequiredTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12ListWorkersRequest\"C\n" +
	"\x13ListWorkersResponse\x12,\n" +
	"\aworkers\x18\x01 \x03(\v2\x12.kaze.WorkerStatusR\aworkers\"\xf9\x02\n" +
	"\fWorkerStatus\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x02R\bcpuUsage\x12&\n" +
	"\x0fram_usage_bytes\x18\x05 \x01(\x03R\rramUsageBytes\x12.\n" +
	"\x13last_heartbeat_unix\x18\x06 \x01(\x03R\x11lastHeartbeatUnix\x12\x1b\n" +
	"\tcpu_count\x18\a \x01(\x05R\bcpuCount\x12\x1b\n" +
	"\tram_bytes\x18\b \x01(\x03R\bramBytes\x120\n" +
	"\x04tags\x18\t \x03(\v2\x1c.kaze.WorkerStatus.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\tcpu_count\x18\x03 \x01(\x05R\bcpuCount\x12\x1b\n" +
	"\tram_bytes\x18\x04 \x01(\x03R\bramBytes\x12.\n" +
	"\x04tags\x18\x05 \x03(\v2\x1a.kaze.WorkerInfo.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"t\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12&\n" +
	"\x0fram_usage_bytes\x18\x03 \x01(\x03R\rramUsageBytes\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xeb\x02\n" +
	"\n" +
	"JobRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1b\n" +
	"\tcron_spec\x18\x04 \x01(\tR\bcronSpec\x12\x1f\n" +
	"\vretry_limit\x18\x05 \x01(\x05R\n" +
	"retryLimit\x12!\n" +
	"\frequired_cpu\x18\x06 \x01(\x02R\vrequiredCpu\x12&\n" +
	"\x0frequired_ram_mb\x18\a \x01(\x03R\rrequiredRamMb\x12G\n" +
	"\rrequired_tags\x18\b \x03(\v2\".kaze.JobRequest.RequiredTagsEntryR\frequiredTags\x1a?\n" +
	"\x11RequiredTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"s\n" +
	"\bLogFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1f\n" +
	"\vstream_type\x18\x04 \x01(\tR\n" +
	"streamType\" \n" +
	"\n" +
	"LogControl\x12\x12\n" +
	"\x04stop\x18\x01 \x01(\bR\x04stop2\xb7\x04\n" +
	"\vKazeService\x12:\n" +
	"\x0eRegisterWorker\x12\x10.kaze.WorkerInfo\x1a\x16.kaze.RegisterResponse\x12<\n" +
	"\tHeartbeat\x12\x16.kaze.HeartbeatRequest\x1a\x17.kaze.HeartbeatResponse\x120\n" +
	"\tSubmitJob\x12\x10.kaze.JobRequest\x1a\x11.kaze.JobResponse\x122\n" +
	"\n" +
	"StreamLogs\x12\x0e.kaze.LogFrame\x1a\x10.kaze.LogControl(\x010\x01\x12B\n" +
	"\vListWorkers\x12\x18.kaze.ListWorkersRequest\x1a\x19.kaze.ListWorkersResponse\x12B\n" +
	"\fGetJobStatus\x12\x19.kaze.GetJobStatusRequest\x1a\x17.kaze.JobStatusResponse\x129\n" +
	"\bListJobs\x12\x15.kaze.ListJobsRequest\x1a\x16.kaze.ListJobsResponse\x12N\n" +
	"\x0fUpdateJobStatus\x12\x1c.kaze.UpdateJobStatusRequest\x1a\x1d.kaze.UpdateJobStatusResponse\x125\n" +
	"\tWatchLogs\x12\x16.kaze.WatchLogsRequest\x1a\x0e.kaze.LogFrame0\x01B\x15Z\x13projects/kaze/protob\x06proto3"

var (
	file_proto_kaze_proto_rawDescOnce sync.Once
	file_proto_kaze_proto_rawDescData []byte
)

func file_proto_kaze_proto_rawDescGZIP() []byte {
	file_proto_kaze_proto_rawDescOnce.Do(func() {
		file_proto_kaze_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kaze_proto_rawDesc), len(file_proto_kaze_proto_rawDesc)))
	})
	return file_proto_kaze_proto_rawDescData
}

var file_proto_kaze_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_kaze_proto_goTypes = []any{
	(*WatchLogsRequest)(nil),        // 0: kaze.WatchLogsRequest
	(*GetJobStatusRequest)(nil),     // 1: kaze.GetJobStatusRequest
	(*ListJobsRequest)(nil),         // 2: kaze.ListJobsRequest
	(*ListJobsResponse)(nil),        // 3: kaze.ListJobsResponse
	(*UpdateJobStatusRequest)(nil),  // 4: kaze.UpdateJobStatusRequest
	(*UpdateJobStatusResponse)(nil), // 5: kaze.UpdateJobStatusResponse
	(*JobStatusResponse)(nil),       // 6: kaze.JobStatusResponse
	(*ListWorkersRequest)(nil),      // 7: kaze.ListWorkersRequest
	(*ListWorkersResponse)(nil),     // 8: kaze.ListWorkersResponse
	(*WorkerStatus)(nil),            // 9: kaze.WorkerStatus
	(*WorkerInfo)(nil),              // 10: kaze.WorkerInfo
	(*RegisterResponse)(nil),        // 11: kaze.RegisterResponse
	(*HeartbeatRequest)(nil),        // 12: kaze.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 13: kaze.HeartbeatResponse
	(*JobRequest)(nil),              // 14: kaze.JobRequest
	(*JobResponse)(nil),             // 15: kaze.JobResponse
	(*LogFrame)(nil),                // 16: kaze.LogFrame
	(*LogControl)(nil),              // 17: kaze.LogControl
	nil,                             // 18: kaze.JobStatusResponse.RequiredTagsEntry
	nil,                             // 19: kaze.WorkerStatus.TagsEntry
	nil,                             // 20: kaze.WorkerInfo.TagsEntry
	nil,                             // 21: kaze.JobRequest.RequiredTagsEntry
}
var file_proto_kaze_proto_depIdxs = []int32{
	6,  // 0: kaze.ListJobsResponse.jobs:type_name -> kaze.JobStatusResponse
	18, // 1: kaze.JobStatusResponse.required_tags:type_name -> kaze.JobStatusResponse.RequiredTagsEntry
	9,  // 2: kaze.ListWorkersResponse.workers:type_name -> kaze.WorkerStatus
	19, // 3: kaze.WorkerStatus.tags:type_name -> kaze.WorkerStatus.TagsEntry
	20, // 4: kaze.WorkerInfo.tags:type_name -> kaze.WorkerInfo.TagsEntry
	21, // 5: kaze.JobRequest.required_tags:type_name -> kaze.JobRequest.RequiredTagsEntry
	10, // 6: kaze.KazeService.RegisterWorker:input_type -> kaze.WorkerInfo
	12, // 7: kaze.KazeService.Heartbeat:input_type -> kaze.HeartbeatRequest
	14, // 8: kaze.KazeService.SubmitJob:input_type -> kaze.JobRequest
	16, // 9: kaze.KazeService.StreamLogs:input_type -> kaze.LogFrame
	7,  // 10: kaze.KazeService.ListWorkers:input_type -> kaze.ListWorkersRequest
	1,  // 11: kaze.KazeService.GetJobStatus:input_type -> kaze.GetJobStatusRequest
	2,  // 12: kaze.KazeService.ListJobs:input_type -> kaze.ListJobsRequest
	4,  // 13: kaze.KazeService.UpdateJobStatus:input_type -> kaze.UpdateJobStatusRequest
	0,  // 14: kaze.KazeService.WatchLogs:input_type -> kaze.WatchLogsRequest
	11, // 15: kaze.KazeService.RegisterWorker:output_type -> kaze.RegisterResponse
	13, // 16: kaze.KazeService.Heartbeat:output_type -> kaze.HeartbeatResponse
	15, // 17: kaze.KazeService.SubmitJob:output_type -> kaze.JobResponse
	17, // 18: kaze.KazeService.StreamLogs:output_type -> kaze.LogControl
	8,  // 19: kaze.KazeService.ListWorkers:output_type -> kaze.ListWorkersResponse
	6,  // 20: kaze.KazeService.GetJobStatus:output_type -> kaze.JobStatusResponse
	3,  // 21: kaze.KazeService.ListJobs:output_type -> kaze.ListJobsResponse
	5,  // 22: kaze.KazeService.UpdateJobStatus:output_type -> kaze.UpdateJobStatusResponse
	16, // 23: kaze.KazeService.WatchLogs:output_type -> kaze.LogFrame
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_kaze_proto_init() }
func file_proto_kaze_proto_init() {
	if File_proto_kaze_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kaze_proto_rawDesc), len(file_proto_kaze_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kaze_proto_goTypes,
		DependencyIndexes: file_proto_kaze_proto_depIdxs,
		MessageInfos:      file_proto_kaze_proto_msgTypes,
	}.Build()
	File_proto_kaze_proto = out.File
	file_proto_kaze_proto_goTypes = nil
	file_proto_kaze_proto_depIdxs = nil
}
