// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: proto/kaze.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CpuCount      int32                  `protobuf:"varint,3,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	RamBytes      int64                  `protobuf:"varint,4,opt,name=ram_bytes,json=ramBytes,proto3" json:"ram_bytes,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_kaze_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerInfo) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *WorkerInfo) GetRamBytes() int64 {
	if x != nil {
		return x.RamBytes
	}
	return 0
}

func (x *WorkerInfo) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_kaze_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsageBytes int64                  `protobuf:"varint,3,opt,name=ram_usage_bytes,json=ramUsageBytes,proto3" json:"ram_usage_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_kaze_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetRamUsageBytes() int64 {
	if x != nil {
		return x.RamUsageBytes
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_kaze_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"` // Optional for Docker driver
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_kaze_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{4}
}

func (x *JobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JobRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *JobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_proto_kaze_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{5}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LogFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	StreamType    string                 `protobuf:"bytes,4,opt,name=stream_type,json=streamType,proto3" json:"stream_type,omitempty"` // stdout or stderr
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFrame) Reset() {
	*x = LogFrame{}
	mi := &file_proto_kaze_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFrame) ProtoMessage() {}

func (x *LogFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFrame.ProtoReflect.Descriptor instead.
func (*LogFrame) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{6}
}

func (x *LogFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LogFrame) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *LogFrame) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *LogFrame) GetStreamType() string {
	if x != nil {
		return x.StreamType
	}
	return ""
}

type LogControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stop          bool                   `protobuf:"varint,1,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogControl) Reset() {
	*x = LogControl{}
	mi := &file_proto_kaze_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogControl) ProtoMessage() {}

func (x *LogControl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kaze_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogControl.ProtoReflect.Descriptor instead.
func (*LogControl) Descriptor() ([]byte, []int) {
	return file_proto_kaze_proto_rawDescGZIP(), []int{7}
}

func (x *LogControl) GetStop() bool {
	if x != nil {
		return x.Stop
	}
	return false
}

var File_proto_kaze_proto protoreflect.FileDescriptor

const file_proto_kaze_proto_rawDesc = "" +
	"\n" +
	"\x10proto/kaze.proto\x12\x04kaze\"\xe8\x01\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\tcpu_count\x18\x03 \x01(\x05R\bcpuCount\x12\x1b\n" +
	"\tram_bytes\x18\x04 \x01(\x03R\bramBytes\x12.\n" +
	"\x04tags\x18\x05 \x03(\v2\x1a.kaze.WorkerInfo.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"t\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12&\n" +
	"\x0fram_usage_bytes\x18\x03 \x01(\x03R\rramUsageBytes\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"X\n" +
	"\n" +
	"JobRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"<\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"s\n" +
	"\bLogFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1f\n" +
	"\vstream_type\x18\x04 \x01(\tR\n" +
	"streamType\" \n" +
	"\n" +
	"LogControl\x12\x12\n" +
	"\x04stop\x18\x01 \x01(\bR\x04stop2\xed\x01\n" +
	"\vKazeService\x12:\n" +
	"\x0eRegisterWorker\x12\x10.kaze.WorkerInfo\x1a\x16.kaze.RegisterResponse\x12<\n" +
	"\tHeartbeat\x12\x16.kaze.HeartbeatRequest\x1a\x17.kaze.HeartbeatResponse\x120\n" +
	"\tSubmitJob\x12\x10.kaze.JobRequest\x1a\x11.kaze.JobResponse\x122\n" +
	"\n" +
	"StreamLogs\x12\x0e.kaze.LogFrame\x1a\x10.kaze.LogControl(\x010\x01B\x15Z\x13projects/kaze/protob\x06proto3"

var (
	file_proto_kaze_proto_rawDescOnce sync.Once
	file_proto_kaze_proto_rawDescData []byte
)

func file_proto_kaze_proto_rawDescGZIP() []byte {
	file_proto_kaze_proto_rawDescOnce.Do(func() {
		file_proto_kaze_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kaze_proto_rawDesc), len(file_proto_kaze_proto_rawDesc)))
	})
	return file_proto_kaze_proto_rawDescData
}

var file_proto_kaze_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_kaze_proto_goTypes = []any{
	(*WorkerInfo)(nil),        // 0: kaze.WorkerInfo
	(*RegisterResponse)(nil),  // 1: kaze.RegisterResponse
	(*HeartbeatRequest)(nil),  // 2: kaze.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: kaze.HeartbeatResponse
	(*JobRequest)(nil),        // 4: kaze.JobRequest
	(*JobResponse)(nil),       // 5: kaze.JobResponse
	(*LogFrame)(nil),          // 6: kaze.LogFrame
	(*LogControl)(nil),        // 7: kaze.LogControl
	nil,                       // 8: kaze.WorkerInfo.TagsEntry
}
var file_proto_kaze_proto_depIdxs = []int32{
	8, // 0: kaze.WorkerInfo.tags:type_name -> kaze.WorkerInfo.TagsEntry
	0, // 1: kaze.KazeService.RegisterWorker:input_type -> kaze.WorkerInfo
	2, // 2: kaze.KazeService.Heartbeat:input_type -> kaze.HeartbeatRequest
	4, // 3: kaze.KazeService.SubmitJob:input_type -> kaze.JobRequest
	6, // 4: kaze.KazeService.StreamLogs:input_type -> kaze.LogFrame
	1, // 5: kaze.KazeService.RegisterWorker:output_type -> kaze.RegisterResponse
	3, // 6: kaze.KazeService.Heartbeat:output_type -> kaze.HeartbeatResponse
	5, // 7: kaze.KazeService.SubmitJob:output_type -> kaze.JobResponse
	7, // 8: kaze.KazeService.StreamLogs:output_type -> kaze.LogControl
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_kaze_proto_init() }
func file_proto_kaze_proto_init() {
	if File_proto_kaze_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kaze_proto_rawDesc), len(file_proto_kaze_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kaze_proto_goTypes,
		DependencyIndexes: file_proto_kaze_proto_depIdxs,
		MessageInfos:      file_proto_kaze_proto_msgTypes,
	}.Build()
	File_proto_kaze_proto = out.File
	file_proto_kaze_proto_goTypes = nil
	file_proto_kaze_proto_depIdxs = nil
}
